service: cruzzie-fastify-api

plugins:
  - serverless-esbuild
  - serverless-dotenv-plugin

useDotenv: true

provider:
  name: aws
  runtime: nodejs18.x
  stage: ${opt:stage}
  region: ap-northeast-1

functions:
  api:
    handler: src/index.handler
    events:
      - httpApi: "*"
